language: ruby
sudo: required
os:
  - osx
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then sudo apt-get update -qq; else brew update; fi
  - if [ $TRAVIS_OS_NAME == "linux" ]; then sudo apt-get install -y ansible -qq; else brew install ansible; fi
script:
  - ansible-playbook $TRAVIS_BUILD_DIR/local.yml -i $TRAVIS_BUILD_DIR/hosts --connection=local
