language: objective-c
sudo: required
os:
  - osx
before_install:
  - brew update
  - brew install python ansible
script:
  - ansible-playbook $TRAVIS_BUILD_DIR/local.yml -i $TRAVIS_BUILD_DIR/hosts --connection=local
