---
- name: login to atom
  command: apm login
  when: ansible_os_family == 'Darwin' and ansible_env.CI is not defined

- name: install starred atom packages
  command: apm stars --install
  when: ansible_os_family == 'Darwin' and ansible_env.CI is not defined

- name: add config.cson
  copy: >
    dest=~/.atom/config.cson
    src=config.cson
  when: ansible_os_family == 'Darwin'
