---
- name: update homebrew
  command: brew update
  when: ansible_os_family == 'Darwin'

- name: add taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - caskroom/cask
    - caskroom/versions
  when: ansible_os_family == 'Darwin'

- name: install CLI tools (OSX)
  homebrew: name={{ item }} state=present
  with_items:
    - git
    - brew-cask
    - wget
    - python
    - node
    - watchman
    - ffmpeg
    - youtube-dl
    - zsh
  when: ansible_os_family == 'Darwin'

- name: install binary casks
  homebrew_cask: name={{ item }} state=present
  with_items:
    - beamer
    - caffeine
    - plex-media-server
    - transmission

- name: add Transmission to Login Items
  command: defaults write loginwindow AutoLaunchedApplicationDictionary -array-add '{ "Path" = "~/Applications/Transmission.app"; "Hide" = 0; }'
