---
- name: install CLI tools
  homebrew: name={{ item }} state=present
  with_items:
    - git
    - s3cmd
    - brew-cask
    - wget
    - heroku-toolbelt
    - hub
    - python
    - ruby
    - node
    - archey
    - the_platinum_searcher
    - brew-gem
    - brew-pip
    - hub
    - imagemagick
    - yuicompressor
    - watchman
    - ffmpeg
    - youtube-dl
  when: ansible_os_family == 'Darwin'

- name: install gem tools
  gem: name={{ item }} state=present
  with_items:
    - jekyll
    - kramdown
  when: ansible_os_family == 'Darwin'

- name: install binary casks
  homebrew_cask: name={{ item }} state=present
  with_items:
    - 1password
    - azure-cli
    - adobe-creative-cloud
    # - adobe-Photoshop-CS6 # no formula in caskroom/versions yet
    - alfred
    - archiver
    - arq
    - atom
    - base
    - beamer
    - keepingyouawake
    - charles
    - chromium
    - dnscrypt
    - doxie
    - dropbox
    - dropletmanager
    - flash
    - flux
    - gitbox
    - google-chrome-canary
    - ios7-screensaver
    - istat-menus
    - java
    - mailbox
    - media-converter # could make its own role and clone the added presets i use
    - openemu-experimental
    - plug
    - sequel-pro
    - sidestep
    - soulver
    - spotify
    - steam
    - tagger
    - transmission
    - transmit
    - vagrant
    - virtualbox
    - visual-studio-code
    - vlc
  when: ansible_os_family == 'Darwin'

- name: apply OS X for hackers settings
  script: osx
  when: ansible_os_family == 'Darwin'

- name: create dirs
  file: name={{ ansible_env.HOME }}/{{ item }} state=directory
  with_items:
    - 'Code'
    - 'Code/scratch'

# TODO: Add apt-get calls for Ubuntu
