---
- name: update apt
  apt: update_cache=yes

- name: install core tools
  apt: name={{ item }} state=present install_recommends=yes
  with_items:
    - build-essential
    - nodejs
    - npm
    - wget
