---
- name: add SSH keys for plex apt
  shell: wget -O - https://dev2day.de/pms/dev2day-pms.gpg.key | sudo apt-key add -

- name: add plex repo
  apt_repository: repo='deb https://dev2day.de/pms wheezy main' state=present
  when: ansible_env.CI is not defined

- name: update apt
  apt: update_cache=yes
  when: ansible_env.CI is not defined

- name: install dependencies
  apt: name={{ item }} state=present
  with_items:
    - libexpat1
    - apt-transport-https

- name: install Plex
  apt: name={{ item }} state=present
  with_items:
    - plexmediaserver
  when: ansible_env.CI is not defined

- name: copy bin script for plex
  copy: >
    dest=/usr/local/bin/plexmediaserver
    src=binscript

- name: make bin script executable
  file: path=/usr/local/bin/plexmediaserver state=touch mode=0774

- name: copy init script for plex
  copy: >
    dest=/etc/init.d/plexmediaserver
    src=initscript

- name: make init script executable
  file: path=/etc/init.d/plexmediaserver state=touch mode=0774

- name: update rc to start plex automatically
  shell: update-rc.d plexmediaserver defaults
